### ISSUE TITLE
Define reasonable default iter & k values

### ISSUE THREAD

**Issue by ErdaradunGaztea** [csprock/Rwclust#13]
It would be much more user-friendly, if there were some default that allows the user to just plug-in the graph and run the algorithm. I saw you using single-digit values, that would give the user an idea about the order of magnitude used here. 

Perhaps these parameters should precede `similarity`, as the latter would probably be changed less often.

On the side note, do you accept pull requests? There are a few things I'd do to make the code more package-like (like replacing `$` accessor with `[[`, since the latter doesn't do unsafe partial matching).

**Comment by csprock** [comment]
Agreed. The authors use single-digit values for both the number of iterations and the number length of the random walks in all of their experiments. I believe that for small graphs single digit values are probably fine and the number of iterations unlikely to effect the results. I suspect that larger values for the length of random walk `k` will be required to achieve decent cluster separation in large graphs. Ideally would like this parameter to have a default that scales with the diameter of the graph. 

However, for now I think that we can just set defaults. 5 for the number of iterations and 3 for the length of the random walks `k` since that should serve as a guide to the user for what a sensible range is for these parameters. 

Could you explain more about unsafe partial matching is in reference to the use of the `$`.

I do accept PRs and contributions are welcome.
