### ISSUE TITLE
0, NaN and NA introduced for degree-1 nodes

### ISSUE THREAD

**Issue by ErdaradunGaztea** [csprock/Rwclust#14]
I was working on upgrading Rwclust and I needed some more tests to make sure that nothing is broken. However, in this simple example 0s are introduced in the 1st iteration, NaNs in the 2nd, and NAs in the 3rd and later ones. I'll try and investigate whether it should happen (and what was written in the original paper).

```{r}
df <- data.frame(
  from = c(1, 1, 2, 3),
  to = c(2, 3, 3, 4),
  weight = c(1, 2, 1, 1)
)
# Any number of `iter` will do, as described above
rwclust(df, iter = 4, k = 1)
```

I'm not sure yet, which property of the graph caused this behaviour.

**Comment by csprock** [comment]
I suspect that this is due to presence of nodes with degree 1. I added a connecting edge to your example graph and it fixed it. I was also able to reproduce the error with the following graph with a degree-1 node.
```
df <- data.frame(
  from = c(1, 1, 2, 3,4,1),
  to = c(2, 3, 3, 4,1,5),
  weight = c(1, 2, 1, ,1,1,1)
)
```

**Comment by csprock** [comment]
I have created up a new branch [fix_issue_14](https://github.com/csprock/Rwclust/tree/fix_issue_14) for work on this. I've included a unit test that must pass for this issue to be resolved.

**Comment by csprock** [comment]
This bug is caused by several interacting subtleties in the algorithm. 

Since 4 is a node of degree 1, the transition matrix for the graph will contain row vector (0, 0, 1, 0) in the 4th row and a row vector (1/2, 1/4, 0, 1/4) in the third row containing the transition probabilities starting from the 4th and 3rd nodes. Since k=1, no powers of this matrix are taken and since the algorithm computes the next iteration's weights based on similarities between the transition probability vectors using the formula

exp(2k - L1(x,y)) - 1 (https://github.com/csprock/Rwclust/blob/master/R/metrics.R#L5)

where the L1-norm. The L1 norm of those two vectors is equal to 2 because these vectors these vectors are orthogonal and sum to 1. 

Therefore the similarity is exp(2(1) - 2) - 1 = exp(0) - 1 = 1 - 1 = 0. This 0 becomes the weight of the edge connecting 4 and 3 in the weight matrix, which results in division by 0 in the second iteration of the algorithm. 

Forcing k > 1 and disallowing random walks of length 1 solves this problem because there will be two matrices summed when the powers of the adjacency matrix are summed here: https://github.com/csprock/Rwclust/blob/master/R/matrix_functions.R#L48 and I believe this will prevent the creation of orthogonal row vectors that sum to 1. 

Putting limits on the number of edges and nodes should also be considered along with testing the algorithm on large numbers of random graphs to look for other pathological cases.
